### ISSUE TITLE
Bug en Footer

### ISSUE THREAD

**Issue by afleones** [hguzman/seguimiento#102]
Corregir el bug del footer, esta superpuesto en el navbar.
![Captura de pantalla 2020-03-20 a las 4 05 19 p m](https://user-images.githubusercontent.com/42587991/77206351-c1749a00-6ac4-11ea-8fe8-862acfd7c519.png)

**Comment by miguelzabalaf** [comment]
Finished with commit b38e54b2d7f1a5f00e1f71db68cd5f0d06105728
