### ISSUE TITLE
Ambientes

### ISSUE THREAD

**Issue by ojsilvera** [hguzman/seguimiento#106]
El index de ambientes, debe colarce debajo de aprendices, trabajando con la ruta anidada del controlador ambiente>anotaciones, para desarrollar el modulo ambientes, que debe listar los ambientes, crear ambientes, actualizarlo, y adicionar anotacion

**Comment by afleones** [comment]
cerrado con commit --> 08f6d90b4b069bb72db4d60ce06a92e704a48285
