### ISSUE TITLE
Estilizar vistas

### ISSUE THREAD

**Issue by ojsilvera** [hguzman/seguimiento#90]
Estilos a las vistas

![estilizar vista cambio de cointraseña](https://user-images.githubusercontent.com/54487801/76777325-08395b80-6776-11ea-9ab4-51eacc7a2dfb.png)

![estilizar vista ambientes index](https://user-images.githubusercontent.com/54487801/76777200-d7592680-6775-11ea-9cc9-de56faa5926b.png)

**Comment by miguelzabalaf** [comment]
Esta tarea la realicé ya anteriormente
