### ISSUE TITLE
Verificar internacionaliizacion

### ISSUE THREAD

**Issue by ojsilvera** [hguzman/seguimiento#91]
Algunas alertas aun se muestran en ingles

![internializacion ](https://user-images.githubusercontent.com/54487801/76777587-69f9c580-6776-11ea-9d29-d0398b874cec.png)

**Comment by afleones** [comment]
Lo que dice es que hay un error en la traducción de pundit.

**Comment by afleones** [comment]
Cerrado con commit --> 6d4cd94b0d32f92c96dca1ddcacee07163b709d5
